name: Build Terminal3

on:
  workflow_dispatch: # 手动触发
  push:
    branches: [ main ]

jobs:
  # ---------------------------------------------------
  # 1. Android 构建任务
  # ---------------------------------------------------

  build-arm64:
    # 指定使用 Docker 容器作为运行环境
    runs-on: ubuntu-latest
    container:
      # 使用 Cirrus Labs 维护的 Flutter ARM 镜像
      image: ghcr.io/cirruslabs/flutter:3.38.2
    steps:
      - uses: actions/checkout@v4
      - run: flutter --version # 此时应该显示正确的ARM版本和Dart 3.17+
      - run: flutter pub get
      - run: flutter build linux --release --target-platform=linux-arm64
  
  build-armgit:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y git clang cmake ninja-build pkg-config libgtk-3-dev

      - name: Clone Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.38.3 --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH

      - name: Accept licenses (optional)
        run: echo "y" | flutter doctor --android-licenses || true

      - name: Verify
        run: flutter --version      

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.13.0
        with:
          flutter-version: 3.38.3 # 使用全局版本变量
          cache: false

      - name: Check
        run: |
          flutter doctor -v
          flutter --version       
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
